[package]
name = "rust-performance"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeresoftx/rust-performance"
description = "Ingeniería de rendimiento en Rust para Jeresoft Academy."
readme = "README.md"

[lib]
name = "rust_performance"
path = "src/lib.rs"

[dependencies]
